/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import { useScoreDataFetcher } from "../../../lib/state/score-context";

export interface ScoringProps {
  quizId: string;
}

export function Scoring({ quizId }: ScoringProps) {
  const { getNumberCorrect, getNumberAnswered, getCurrentStreak } =
    useScoreDataFetcher();

  const numberCorrect = getNumberCorrect(quizId);
  const numberAnswered = getNumberAnswered(quizId);
  const currentStreak = getCurrentStreak(quizId);

  return (
    <div className="w-full">
      <div className="max-w-2xl mx-auto flex justify-between items-center px-4 py-2">
        <div className="text-sm text-gray-500 dark:text-gray-400">
          Correct:{" "}
          <span className="font-bold text-correct">
            {numberCorrect} (
            {numberAnswered === 0
              ? 0
              : Math.round((numberCorrect / numberAnswered) * 100)}
            %)
          </span>
        </div>
        <div className="text-sm text-gray-500 dark:text-gray-400">
          Streak:{" "}
          <span className="font-bold text-correct">{currentStreak}</span>
        </div>
        <div className="text-sm text-gray-500 dark:text-gray-400">
          Incorrect:{" "}
          <span className="font-bold text-incorrect">
            {numberAnswered - numberCorrect} (
            {numberAnswered === 0
              ? 0
              : Math.round(
                  ((numberAnswered - numberCorrect) / numberAnswered) * 100,
                )}
            %)
          </span>
        </div>
      </div>
    </div>
  );
}
