"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import { sampleSize } from "lodash";
import { TestFramework } from "@/components/component/test-framework";
import { Note } from "tone/Tone/core/type/Units";

export const ChordMap: Record<string, Note[]> = {
  "C Minor": ["C4", "Eb4", "G4"],
  "C Major": ["C4", "E4", "G4"],
};

export function ChordTest() {
  const notes = Object.keys(ChordMap) as Note[];

  return (
    <TestFramework
      headline={"Identify the chord"}
      getOptions={() =>
        sampleSize(notes, 4).map((x) => ({
          text: x,
          notes: ChordMap[x],
          asChord: true,
        }))
      }
    />
  );
}
