/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import {Button} from "@/components/ui/button"
import {PlayNote} from "@/components/tone/play-note";
import {Note} from "tone/Tone/core/type/Units";
import {sample, sampleSize} from "lodash";

export function Correct() {


    return (
        <div className="w-full flex flex-col items-center gap-4">
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-gray-100">Correct Answer!</h2>
            <CheckIcon className="w-24 h-24 text-green-500 dark:text-green-300"/>
            <p className="text-lg text-gray-700 dark:text-gray-300">Great job! You've identified the note correctly.</p>
        </div>
    )
}


function CheckIcon(props: { className: string }) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <polyline points="20 6 9 17 4 12" />
        </svg>
    )
}