/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UIXvmXomXbD
 */
import { LinkButton } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";
import { ResponsiveLine } from "@/lib/nivo/line";
import { HTMLAttributes } from "react";

export function Dashboard() {
  return (
    <main className="p-6 grid gap-6">
      <div className="grid gap-4">
        <h2 className="text-xl font-semibold text-gray-800 dark:text-gray-100">
          Exercises
        </h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card className="bg-white dark:bg-gray-900 shadow-md">
            <CardContent className="p-4">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                Identify Notes
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                Test your ability to recognize individual notes.
              </p>
              <LinkButton href={"/notes"} className="mt-4" variant="outline">
                Start Exercise
              </LinkButton>
            </CardContent>
          </Card>
          <Card className="bg-white dark:bg-gray-900 shadow-md">
            <CardContent className="p-4">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                Identify Intervals
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                Test your ability to recognize intervals between notes.
              </p>
              <LinkButton href={"/interval"} className="mt-4" variant="outline">
                Start Exercise
              </LinkButton>
            </CardContent>
          </Card>
          <Card className="bg-white dark:bg-gray-900 shadow-md">
            <CardContent className="p-4">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                Identify Chords
              </h3>
              <p className="text-gray-600 dark:text-gray-300">
                Test your ability to recognize different chords.
              </p>
              <LinkButton href={"/chord"} className="mt-4" variant="outline">
                Start Exercise
              </LinkButton>
            </CardContent>
          </Card>
        </div>
      </div>
      <div className="grid gap-4">
        <h2 className="text-xl font-semibold text-gray-800 dark:text-gray-100">
          Progress (Not working yet)
        </h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          <Card className="bg-white dark:bg-gray-900 shadow-md">
            <CardContent className="p-4">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                Notes Progress
              </h3>
              <CurvedlineChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
          <Card className="bg-white dark:bg-gray-900 shadow-md">
            <CardContent className="p-4">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                Intervals Progress
              </h3>
              <CurvedlineChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
          <Card className="bg-white dark:bg-gray-900 shadow-md">
            <CardContent className="p-4">
              <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                Chords Progress
              </h3>
              <CurvedlineChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
        </div>
      </div>
    </main>
  );
}

function CurvedlineChart(props: HTMLAttributes<HTMLDivElement>) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "B",
            data: [
              { x: "2018-01-01", y: 7 },
              { x: "2018-01-02", y: 5 },
              { x: "2018-01-03", y: 11 },
              { x: "2018-01-04", y: 9 },
              { x: "2018-01-05", y: 12 },
              { x: "2018-01-06", y: 16 },
              { x: "2018-01-07", y: 13 },
              { x: "2018-01-08", y: 13 },
            ],
          },
          {
            id: "A",
            data: [
              { x: "2018-01-01", y: 9 },
              { x: "2018-01-02", y: 8 },
              { x: "2018-01-03", y: 13 },
              { x: "2018-01-04", y: 6 },
              { x: "2018-01-05", y: 8 },
              { x: "2018-01-06", y: 14 },
              { x: "2018-01-07", y: 11 },
              { x: "2018-01-08", y: 12 },
            ],
          },
        ]}
        enableCrosshair={false}
        margin={{ top: 50, right: 110, bottom: 50, left: 60 }}
        xScale={{
          type: "time",
          format: "%Y-%m-%d",
          useUTC: false,
          precision: "day",
        }}
        xFormat="time:%Y-%m-%d"
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "X",
          legendOffset: 45,
          legendPosition: "middle",
          format: "%b %d",
          tickValues: "every 1 day",
        }}
        axisLeft={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "Y",
          legendOffset: -45,
          legendPosition: "middle",
        }}
        colors={{ scheme: "paired" }}
        pointSize={5}
        pointColor={{
          from: "color",
          modifiers: [["darker", 0.2]],
        }}
        pointBorderWidth={2}
        pointBorderColor={{
          from: "color",
          modifiers: [["darker", 0.2]],
        }}
        pointLabelYOffset={-12}
        useMesh={true}
        curve="monotoneX"
        legends={[
          {
            anchor: "bottom-right",
            direction: "column",
            justify: false,
            translateX: 100,
            translateY: 0,
            itemsSpacing: 0,
            itemDirection: "left-to-right",
            itemWidth: 80,
            itemHeight: 20,
            symbolSize: 14,
            symbolShape: "circle",
          },
        ]}
        theme={{
          tooltip: {
            container: {
              fontSize: "12px",
            },
          },
        }}
        role="application"
      />
    </div>
  );
}
