"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import { TestFramework } from "@/components/component/test-framework";
import { NoteMap } from "@/lib/note-map";

export function NoteTest() {
  return (
    <TestFramework
      headline={"Identify the note"}
      noteMapping={NoteMap}
    />
  );
}
