"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import { sampleSize } from "lodash";
import { TestFramework } from "@/components/component/test-framework";
import { BaseNote, NoteMap } from "@/lib/note-map";

export function NoteTest() {
  const notes = Object.keys(NoteMap) as BaseNote[];

  return (
    <TestFramework
      headline={"Identify the note"}
      getOptions={() =>
        sampleSize(notes, 4).map((x) => ({
          notes: [NoteMap[x]],
          text: x,
        }))
      }
    />
  );
}
