/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import { Button } from "@/components/ui/button";
import { useScoreStore } from "../util/score-context";
import { useShallow } from "zustand/react/shallow";

export function Scoring() {
  const { getNumberCorrect, getNumberAnswered, currentStreak, totalQuestions } =
    useScoreStore(
      useShallow((state) => ({
        getNumberCorrect: state.getNumberCorrect,
        getNumberAnswered: state.getNumberAnswered,
        currentStreak: state.currentStreak,
        totalQuestions: state.totalQuestions,
      }))
    );
  const numberCorrect = getNumberCorrect();
  const numberAnswered = getNumberAnswered();
  return (
    <div className="w-full max-w-2xl mx-auto flex justify-between items-center px-4 py-2">
      <div className="text-sm text-gray-500 dark:text-gray-400">
        Correct:{" "}
        <span className="font-bold text-correct">
          {numberCorrect} (
          {numberAnswered === 0
            ? 0
            : Math.round((numberCorrect / numberAnswered) * 100)}
          %)
        </span>
      </div>
      <div className="text-sm text-gray-500 dark:text-gray-400">
        Streak: <span className="font-bold text-correct">{currentStreak}</span>
      </div>
      <div className="text-sm text-gray-500 dark:text-gray-400">
        Answered:{" "}
        <span className="font-bold text-primary">
          {numberAnswered}/{totalQuestions}
        </span>
      </div>
      <div className="text-sm text-gray-500 dark:text-gray-400">
        Incorrect:{" "}
        <span className="font-bold text-incorrect">
          {numberAnswered - numberCorrect} (
          {numberAnswered === 0
            ? 0
            : Math.round(
                ((numberAnswered - numberCorrect) / numberAnswered) * 100
              )}
          %)
        </span>
      </div>
    </div>
  );
}
