"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import { QuizFramework } from "@/components/quizes/framework/quiz-framework";
import { Note } from "tone/Tone/core/type/Units";

export const ChordMap: Record<string, Note[]> = {
  "C Minor": ["C4", "Eb4", "G4"],
  "C Major": ["C4", "E4", "G4"],
};

export function ChordQuiz() {
  return (
    <QuizFramework
      headline={"Identify the chord"}
      noteMapping={ChordMap}
      asChord
    />
  );
}
