/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import { QuizFramework } from "@/components/quizes/framework/quiz-framework";
import { NoteList } from "@/lib/note-map";
import { QuizOption } from "@/lib/quiz/quiz-option";

export function getNoteQuizOptions() {
  const allOptions = NoteList.map((note): QuizOption => {
    return {
      uniqueId: note,
      key: note,
      text: note,
      hintText: "",
      notes: [note],
    };
  });

  return allOptions;
}

export function NoteQuiz() {
  return (
    <QuizFramework
      quizId="notes"
      headline={"Identify the note"}
      getQuizOptions={getNoteQuizOptions}
      preventSameAnswer
    />
  );
}
