"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejwRzEw5Z0k
 */
import { QuizFramework } from "@/components/component/quiz-framework";
import { NoteMap } from "@/lib/note-map";

export function NoteQuiz() {
  return (
    <QuizFramework
      headline={"Identify the note"}
      noteMapping={NoteMap}
    />
  );
}
